config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :tours
  resources :operators

  get '/get_tour_types' => 'tours#get_tour_types'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/operator.rb
class Operator < ApplicationRecord
  has_many :tours
end

app/models/tour.rb
class Tour < ApplicationRecord
  belongs_to :operator, optional: true

validates_presence_of :start_datetime, :end_datetime, :tour_type

validate :end_date_is_after_start_date
validate :recurrence_date

def tour_length
  if start_datetime.present? && end_datetime.present?
    TimeDifference.between(start_datetime, end_datetime).humanize
  end
end

private

  def end_date_is_after_start_date
    return if end_datetime.blank? || start_datetime.blank?

      if end_datetime < start_datetime
        errors.add(:end_datetime, "cannot be before the start date")
      end
    end
  end

  def recurrence_date
    return if recurring.blank?

    if recurring == 'On' && recurring_date.blank?
      errors.add(:recurring_date, "cannot be blank is recurrence is On") 
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: [:destroy]

  def index
    @tours = Tour.all
  end

  def new
    @tour = Tour.new
    @tour_types = ['Daily']
  end

  def create
    if params[:tour][:recurring_times].present? || params[:tour][:recurring_date].present?
      create_tours
    else
      Tour.create(tour_params)
    end
    redirect_to tours_path
  end

  def destroy
    redirect_to tours_path if @tour.destroy
  end

  def get_tour_types
    @tour_types = get_types
  end

  private

  def set_tour
    @tour = Tour.find_by(id: params[:id])
  end

  def tour_params
    params.require(:tour).permit(:start_datetime, :end_datetime, :tour_type, :recurring, :recurring_date, :recurring_times)
  end

  def get_types
    if params[:start_date].present?
       @start_date = params[:start_date].to_date
       day   = @start_date.strftime("%A")
       month = Date::MONTHNAMES[@start_date.month]
       date = @start_date.day
       week_of_month = find_day_position(@start_date)
      ['Daily', "Weekly on #{day}", "Monthly on Every #{date}", "on Every #{week_of_month} #{day}", "Annually on #{month} #{date}"]
    end
  end

  def create_tours
    tour_type = params[:tour][:tour_type]
    Tour.create(tour_params)
    if tour_type == 'Daily'
      create_daily_tour
    elsif(tour_type.include? "Weekly")
      create_weekly_tour
    elsif(tour_type.include? "Monthly")
      create_monthly_tour
    elsif(tour_type.include? "Annually")
      create_yearly_tour
    elsif(tour_type.include? "Every")
      create_week_month_tours
    end
  end

  def set_params_data
    set_params

    if params[:tour][:recurring_times].present?
      @count = params[:tour][:recurring_times].to_i
    elsif params[:tour][:recurring_date].present?
      if @tour_type == 'Daily'
        @count = TimeDifference.between(@start_datetime, @recurring_date).in_days
      elsif (@tour_type.include? "Weekly")
        @count = TimeDifference.between(@start_datetime, @recurring_date).in_weeks
      elsif(@tour_type.include? "Monthly")
        @count = TimeDifference.between(@start_datetime, @recurring_date).in_months
      elsif(@tour_type.include? "Annually")
        @count = TimeDifference.between(@start_datetime, @recurring_date).in_years
      elsif(@tour_type.include? "Every")
        @count = TimeDifference.between(@start_datetime, @recurring_date).in_months
      end
    end
  end

  def set_params
    @tour_type = params[:tour][:tour_type]
    @start_datetime = params[:tour][:start_datetime]
    @end_datetime   = params[:tour][:end_datetime]
    @recurring_date = params[:tour][:recurring_date]
  end

  def create_daily_tour
   set_params_data
    if @count > 1
        @date_counter = 1
      (@count-1).to_i.times do
        create_tour(@start_datetime.to_date, @end_datetime.to_date, @date_counter, @tour_type)
        @date_counter = @date_counter + 1
      end
    end
  end

  def create_weekly_tour
    set_params_data

    if @count > 1
        @date_counter = 7
      (@count-1).to_i.times do
        create_tour(@start_datetime.to_date, @end_datetime.to_date, @date_counter, @tour_type)
        @date_counter = @date_counter + 7
      end
    end
  end

  def create_monthly_tour
    set_params_data
    
    if @count > 1
        @date_counter = 1.month
      (@count-1).to_i.times do
        create_tour(@start_datetime.to_date, @end_datetime.to_date, @date_counter, @tour_type)
        @date_counter = @date_counter + 1.month
      end
    end
  end

  def create_yearly_tour
    set_params_data

    if @count > 1
        @date_counter = 1.year
      @count.to_i.times do
        create_tour(@start_datetime.to_date, @end_datetime.to_date, @date_counter, @tour_type)
        @date_counter = @date_counter + 1.year
      end
    end
  end

  def create_week_month_tours
    set_params_data

    if @count > 1
        @date_counter = 1.month
        current_month = current_month_day(@start_datetime.to_date)
        @index = current_month.find_index(@start_datetime.to_date.day) + 1
      @count.to_i.times do
        day_position = day_position(@start_datetime.to_date, @date_counter)
        next_date = day_position[@index-1]
        next_month = (@start_datetime.to_date + @date_counter).month
        next_year = (@start_datetime.to_date + @date_counter).year
        Tour.create!(start_datetime: "#{next_year}/#{next_month}/#{next_date} #{@start_datetime.to_time.strftime("%H:%M")}", end_datetime: @end_datetime.to_date + @date_counter, tour_type: @tour_type)
        @date_counter = @date_counter + 1.month
      end
    end
  end

  def create_tour(start_datetime, end_datetime, date_counter, tour_type)
    Tour.create!(start_datetime: start_datetime + date_counter, end_datetime: end_datetime + date_counter, tour_type: tour_type)
  end

### Functions to find dates and months

  def current_month_day(start_datetime)
    weekday_name = start_datetime.strftime("%A").downcase
    (start_datetime).send("all_#{weekday_name}s_in_month")
  end

  def day_position(start_date, date_counter)
    weekday_name = start_date.strftime("%A").downcase
    (start_date + date_counter).send("all_#{weekday_name}s_in_month")
   end

  def find_day_position(start_date)
    weekday_name = start_date.strftime("%A").downcase
    arr = start_date.send("all_#{weekday_name}s_in_month")
    arr.find_index(start_date.day) + 1
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventBooking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tours/_form.html.erb
<div class="container-fluid mt--6">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-header border-0">
          <h3 class="mb-0">Tours New</h3>
          <%= form_with(model: @tour, local: true) do |form| %>
          <% if @tour.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@tour.errors.count, "error") %> prohibited this Tour from being saved:</h2>

            <ul>
              <% @tour.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
          <% end %>
          <div class="form-group">
            <%= form.label :start_datetime %>
            <%= form.text_field :start_datetime, id: "datepicker", class: "form-control date-value datetimepicker", autocomplete:'off' %>
          </div>

          <% if tour_types.present? %>
            <div class="form-group tour-types" id= 'tour-t'>
              <%= form.label :tour_type %>
              <%= form.select :tour_type, tour_types, class: "form-control" %>
            </div>
          <% end %>

          <div class="form-group">
            <%= form.label :end_datetime %>
            <%= form.text_field :end_datetime, class: "form-control datetimepicker", autocomplete:'off' %>
          </div>


          <div class="form-group">
            <%= form.label :recurrence %>
            <%= form.select :recurring, ['Never', 'Fill Occurence date', 'No. of occurences'], class: "form-control" %>
          </div>

          <div class="form-group d-none" id= 'recurring'>
            <%= form.label :recurring_date %>
            <%= form.text_field :recurring_date, class: "form-control datetimepicker", autocomplete:'off' %>
          </div>

          <div class="form-group d-none" id= 'recurring-times'>
            <%= form.label :recurring_times %>
            <%= form.number_field :recurring_times, class: "form-control", autocomplete:'off' %>
          </div>

          <div class="form-group">
            <%= form.submit class: "btn btn-primary" %>
          </div>
        <% end %>
        </div>
    </div>
  </div>
</div>

<script>
  $('.datetimepicker').datetimepicker();

  $('body').on('change', '.date-value', function(){
    var date = $('#datepicker').val();
    $.ajax({
        url: "/get_tour_types",
        type: "GET",
        data: { start_date: date }
    })
  });

  $('body').on('change', '#tour_recurring', function(){
    var valu = $('#tour_recurring').val();
    if (valu == 'Fill Occurence date'){
      $('#recurring').removeClass('d-none');
      $('#recurring-times').addClass('d-none');
    }
    else if(valu == 'No. of occurences') {
      $('#recurring-times').removeClass('d-none');
      $('#recurring').addClass('d-none');
    }
    else {
      $('#recurring').addClass('d-none');
    }
  });
</script>

app/views/tours/_tour_types.html.erb
<%= form.label :tour_type %>
<%= form.select :tour_type, tour_types, class: "form-control" %>

app/views/tours/get_tour_types.js.erb
$("#tour_tour_type").empty();
<% @tour_types.each do |tour_type| %>
  $("<option></option>").attr("value", "<%= tour_type %>").text("<%= tour_type %>").appendTo('#tour_tour_type');
<% end %>

app/views/tours/index.html.erb
<div class="container">
  <h2>Tour</h2>
  <%= link_to 'Create Tour', new_tour_path, class: "btn btn-primary" %>   
  <div class="table-responsive">          
  <table class="table">
    <thead>
      <tr>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Tour Type</th>
        <th>Recurrence</th>
        <th>Recurrence Date</th>
        <th>Tour Length</th>
        <th>No. of occurences</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
    	<% @tours.each do |tour| %>
	      <tr>
	        <td><%= tour.start_datetime %></td>
	        <td><%= tour.end_datetime %></td>
	        <td><%= tour.tour_type %></td>
	        <td><%= tour.recurring %></td>
	        <td><%= tour.recurring_date %></td>
	        <td><%= tour.tour_length %></td>
	        <td><%= tour.recurring_times %></td>
          <td><%= link_to 'Delete', tour_path(tour), method: :delete, class: "btn btn-primary" %> </td>
	      </tr>
      <% end %>
    </tbody>
  </table>
  </div>
</div>

app/views/tours/new.html.erb
<div class= 'tour-form'>
  <%= render 'form', tour_types: @tour_types %>
</div>